# docker-compose의 버전을 명시. 버전별로 명령어등의 약간의 차이가 있다.
version: "2.1"

services:
    nginx:
        # 만들어질 container 이름
        container_name: nginx

        # Dockerfile의 위치
        build: ./nginx

        # 컨테이너 끼리 내부적으로 연결할 때의 alias
        # 예를 들어 A:B 의 경우 이 컨테이너 내에서 B라는 이름으로 A에 연결 할 수 있다.
        # 여기서는 nginx에서 app이라는 도메인을 통해서 app 컨테이너에 접근할 수 있다.
        links:
            - app:app

        # 열어줄 포트
        # 호스트와 연결할 포트:외부에 노출할 포트
        ports:
            - 80:80
        
    app:
        container_name: app
        build: .

        # 환경변수를 지정할 수 있음.
        environment:
            NODE_ENV: localhost
        ports:
            - 3000