apiVersion: v1

kind: ReplicationController

metadata:

  name: chatbot-node5-rc

spec:

  replicas: 3

  selector:

    app: chatbot-node5

  template:

    metadata:

      name: chatbot-node5-pod

      labels:

        app: chatbot-node5

    spec:

      containers:

      - name: chatbot-node5

        image: gcr.io/bamboo-velocity-278205/chatbot-node5:v8

        imagePullPolicy: Always

        command: 
        ports:

        - containerPort: 8080