apiVersion: v1

kind: Service

metadata:

  name: chatbot-node5-svc

spec:

  selector:

    app: chatbot-node5

  ports:

    - port: 80

      protocol: TCP

      targetPort: 8080

  type: LoadBalancer